name:                usecaseAAPad
version:             0.1.0.0
github:              "L-Solutions/ExampleAAPad"
license:             BSD3
author:              "Benoît Fraikin"
maintainer:          "benoit.fraikin@usherbrooke.ca"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/L-Solutions/ExampleAAPad#readme>

dependencies:
- base >= 4.7 && < 5
- mtl > 2.2
- parsec > 3
- semigroupoids > 5.3
- text > 1.2
- textdecoration >= 0.1

library:
    source-dirs:    src

executables:
    usecaseAAPad-exe:
        main:                Main.hs
        source-dirs:         app
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - usecaseAAPad

tests:
  PAD-test:
    main: Spec-PAD.hs
    source-dirs: test
    ghc-options:
    - -threaded
    dependencies:
    - usecaseAAPad

  Integration-test:
    main: Test-Suite_PAD-Automaton.hs
    source-dirs: test
    ghc-options:
    - -threaded
    dependencies:
    - usecaseAAPad

